setup/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from clientes.views import cadastro_com_endereco,cadastro_sem_endereco,cadastro_endereco,clientes
from pedidos.views import pedido,pedidos,tirar_item,adicionar_item,mudar_status,imprimir,todos_pedidos,escolher_endereco,desconto
from vendedores.views import login,logout,dashboard

urlpatterns = [

    path('admin/', admin.site.urls),
    path('clientes', clientes, name='clientes'),
    path('pedidos', todos_pedidos, name='pedidos'),
    path('dashboard', dashboard, name='dashboard'),
    path('', dashboard, name='dashboard'),
    path('cadastro_com_endereco', cadastro_com_endereco, name='cadastro_com_endereco'),
    path('cadastro_sem_endereco', cadastro_sem_endereco, name='cadastro_sem_endereco'),
    path('cadastro_endereco/<int:id>', cadastro_endereco, name='cadastro_endereco'),
    path('pedidos/<slug:cliente>', pedidos, name='pedidos'),
    path('pedido/<slug:cliente>/<int:pedido>/', pedido, name='pedido'),
    path('pedido/<slug:cliente>/<int:pedido>/tirar_item', tirar_item, name='tirar_item'),
    path('pedido/<slug:cliente>/<int:pedido>/adicionar_item', adicionar_item, name='adicionar_item'),
    path('pedido/<slug:cliente>/<int:pedido>/escolher_endereco', escolher_endereco, name='escolher_endereco'),
    path('pedido/<slug:cliente>/<int:pedido>/desconto', desconto, name='desconto'),
    path('pedido/<slug:cliente>/<int:pedido>/mudar_status', mudar_status, name='mudar_status'),
    path('pedido/<slug:cliente>/<int:pedido>/imprimir', imprimir, name='imprimir'),
    path('accounts/login', login, name='login'),
    path('logout', logout, name='logout'),

]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/models.py
from django.db import models
from vendedores.models import Vendedor
from django.utils.text import slugify


class Cliente(models.Model):
    vendedor = models.ForeignKey(Vendedor, on_delete=models.CASCADE)
    nome = models.CharField(max_length=80)
    telefone = models.IntegerField(blank= True, null=True)
    email = models.EmailField(blank= True, null=True)
    cpf = models.IntegerField(blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwargs)



class Endereco(models.Model):
    UF = (
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'))



    cliente = models.ForeignKey(Cliente, on_delete= models.CASCADE)
    destinatario = models.CharField(max_length= 30, null=True, blank=True)
    apelido = models.CharField(max_length= 30, default= 'Endereço principal', blank=True)
    cep = models.IntegerField()
    logradouro = models.CharField(max_length=150)
    numero = models.CharField(max_length=5)
    bairro = models.CharField(max_length=30)
    uf = models.CharField(max_length = 2, choices=UF, null= True)
    complemento = models.CharField(max_length=30, default='sem completmento',blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    ativo = models.BooleanField(default=False)

    def __str__(self):
        return self.cliente.nome + ' ' + self.apelido

    @property
    def destinatario_auto(self):
        if self.destinatario == None:
            return self.cliente.nome
        else:
            return self.destinatario

clientes/forms.py
from django import forms

from .models import Endereco, Cliente


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ('nome', 'telefone', 'email', 'cpf',)



class EnderecoForm(forms.ModelForm):
     class Meta:
        model = Endereco
        fields = ('destinatario','apelido','cep','logradouro','numero','bairro','uf','complemento')
        # widgets = {'cliente': forms.HiddenInput()}

clientes/views.py
from django.shortcuts import render, redirect
from .models import Endereco, Cliente
from .forms import EnderecoForm, ClienteForm
from vendedores.models import Vendedor
from django.contrib import messages
from pedidos.models import Pedido
from django.contrib.auth.decorators import login_required
import datetime
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import io
import urllib, base64
from mpl_toolkits.axes_grid1.axes_divider import make_axes_area_auto_adjustable

@login_required
def clientes(request):
    clientes = Cliente.objects.filter(vendedor=request.user.vendedor.id)

    # inicio pandas vendas por estado
    cliente_df = Cliente.objects.filter(vendedor_id=request.user.vendedor.id).values('endereco__uf')

    df = pd.DataFrame(cliente_df).value_counts()

    fig, ax = plt.subplots()
    # ax = fig.add_axes([0, 0, 1, 1])
    ax.set_yticks(range(1, len(df)))
    make_axes_area_auto_adjustable(ax)

    df.plot( kind='bar', figsize=(13,5),title='Cliente por estado', x='endereco__uf', colormap='prism')
    plt.title("Clientes por estado")
    plt.xlabel('Estado')
    plt.xticks(rotation=0)
    buffer = io.BytesIO()
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    image_png = buffer.getvalue()
    buffer.close()
    graphic = base64.b64encode(image_png)
    graphic = graphic.decode('utf-8')
    # fim pandas

    # inicio pandas valor por cliente
    cliente_df_compra = Pedido.objects.filter(vendedor_id=request.user.vendedor.id, pagamento=True).values('cliente__nome','valor')


    df_valor = pd.DataFrame(cliente_df_compra)
    df_valor['valor'] = df_valor['valor'].astype(float)
    df_valor['cliente__nome'] = df_valor['cliente__nome'].astype(str)

    #
    print(df_valor)
    print(df_valor.dtypes)
    df_valor = df_valor.groupby('cliente__nome').sum()
    fig_valor, ax_valor = plt.subplots()
    # ax_valor = fig_valor.add_axes([0, 0, 1, 1])
    # ax_valor.set_yticks(range(1, len(df_valor)))
    make_axes_area_auto_adjustable(ax_valor)

    df_valor.plot(kind='bar', figsize=(13,7),title='Cliente por estado', colormap='prism')
    plt.xticks(rotation=0)
    plt.title("Valor de compra")
    plt.xlabel('cliente')

    buffer_valor = io.BytesIO()
    plt.savefig(buffer_valor, format='png')
    buffer_valor.seek(0)
    image_png_valor = buffer_valor.getvalue()
    buffer_valor.close()
    graphic_valor = base64.b64encode(image_png_valor)
    graphic_valor = graphic_valor.decode('utf-8')
    # fim pandas


    # if request.method == "POST":#adiciona pedido para cliente
    #
    #     cliente = request.POST['cliente_id']
    #     print(cliente)
    #     vendedor_id = request.user.id
    #     cli = Cliente.objects.get(id=cliente)
    #     ven = Vendedor.objects.get(id=vendedor_id)
    #     pedidos = Pedido.objects.filter(cliente_id=cliente)
    #     if not pedidos:
    #         print("PRimeiRO Pedido")
    #         novo_pedido = Pedido(cliente=cli, vendedor=ven, primeira_compra=True)
    #         novo_pedido.save()
    #         return redirect(f"/pedido/{cli.slug}/{novo_pedido.id}")
    #     else:
    #         print("JA TEM PEDIDOS")
    #         novo_pedido = Pedido(cliente=cli, vendedor=ven)
    #         novo_pedido.save()
    #         return redirect(f"/pedido/{cli.slug}/{novo_pedido.id}")
    #     return redirect(f"/pedido/{cli.slug}/{novo_pedido.id}")


    return render(request=request, template_name="clientes.html", context={ 'clientes': clientes,'graphic':graphic, 'graphic_valor': graphic_valor})
@login_required
def cadastro_sem_endereco(request):
    if request.method == "POST":
        cliente_form = ClienteForm(request.POST)
        if cliente_form.is_valid():
            cliente_form.save()
            messages.success(request, ('O endereço foi salvo!'))
        else:
            messages.error(request, 'Error salvar o formulario')
            return redirect("cadastro_sem_endereco")
    cliente_form = ClienteForm()

    return render(request=request, template_name="cadastro_sem_endereco.html",
                  context={ 'cliente_form': cliente_form})

@login_required
def cadastro_com_endereco(request):
    if request.method == "POST":
        cliente_form = ClienteForm(request.POST)
        endereco_form = EnderecoForm(request.POST)

        if endereco_form.is_valid() and cliente_form.is_valid():

            vendedor_id =  request.user.vendedor.id
            # print(vendedor_id)
            vendedor =  Vendedor.objects.get(id=vendedor_id)
            # print(vendedor)
            nome = cliente_form.cleaned_data['nome']
            telefone = cliente_form.cleaned_data['telefone']
            email = cliente_form.cleaned_data['email']
            cpf = cliente_form.cleaned_data['cpf']

            apelido = endereco_form.cleaned_data['apelido']
            cep = endereco_form.cleaned_data['cep']
            logradouro = endereco_form.cleaned_data['logradouro']
            numero = endereco_form.cleaned_data['numero']
            bairro = endereco_form.cleaned_data['bairro']
            uf = endereco_form.cleaned_data['uf']

            cliente = Cliente.objects.create(
                vendedor=vendedor,
                nome=nome,
                telefone=telefone,
                email=email,
                cpf=cpf,

            )

            # cliente = cliente.save(commit=False)


            form = Endereco(cliente=cliente,
                     apelido=apelido,
                     cep=cep,
                     logradouro=logradouro,
                     numero=numero,
                     bairro=bairro,
                     uf=uf,
                     complemento = "teste 123"
                            )



            cliente.save()
            form.save()
            messages.success(request, ('O endereço foi salvo!'))
            return redirect("dashboard")
        else:
            messages.error(request, 'Error salvar o formulario')

        return redirect("cadastro_com_endereco")
    endereco_form = EnderecoForm()
    cliente_form = ClienteForm()
    endereco = Endereco.objects.all()
    return render(request=request, template_name="cadastro_com_endereco.html", context={'endereco_form': endereco_form, 'endereco': endereco, 'cliente_form':cliente_form})

@login_required
def cadastro_endereco(request, id):
    if request.method == "POST":
        cliente = Cliente.objects.get(id=id)
        # print(cliente)
        endereco_form = EnderecoForm(request.POST)

        if endereco_form.is_valid():

            # cliente = endereco_form.cleaned_data['cliente']
            apelido = endereco_form.cleaned_data['apelido']
            cep = endereco_form.cleaned_data['cep']
            logradouro = endereco_form.cleaned_data['logradouro']
            numero = endereco_form.cleaned_data['numero']
            bairro = endereco_form.cleaned_data['bairro']
            uf = endereco_form.cleaned_data['uf']



            form = Endereco(cliente=cliente,
                     apelido=apelido,
                     cep=cep,
                     logradouro=logradouro,
                     numero=numero,
                     bairro=bairro,
                     uf=uf,
                     complemento = "teste 123"
                            )


            form.save()
            messages.success(request, ('O endereço foi salvo!'))
        else:
            messages.error(request, 'Error salvar o formulario')

        return redirect("clientes")
    endereco_form = EnderecoForm()
    endereco = Endereco.objects.all()
    return render(request=request, template_name="cadastro_endereco.html", context={'endereco_form': endereco_form, 'endereco': endereco})

templates/base.html
<!doctype html>
{% load static %}

<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vendas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
  </head>
  <body>
  {% include 'partials/_navbar.html' %}
  {% block content %} {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

templates/cadastro_com_endereco.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--Importando Script Jquery-->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

{% load widget_tweaks %}
<div class="container border my-5">

    <form method="post">
        {% csrf_token %}
        {% for hidden_field in cliente_form.hidden_fields %}
        {{ hidden_field }}
        {% endfor %}
        {% for hidden_field in endereco_form.hidden_fields %}
        {{ hidden_field }}
        {% endfor %}

        {% if endereco_form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in cliente_form.non_field_errors %}
            {{ error }}
            {% endfor %}
            {% for error in endereco_form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        {% endif %}
        <div class="row ">
            <div class="col-12 bg-danger  text-white text-center"><h3>CLIENTE</h3></div>
            {% for field in cliente_form.visible_fields %}
            <div class="form-group col-6">
                {{ field.label_tag }}

                {% if cliente_form.is_bound %}
                {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
                {% endfor %}
                {% else %}
                {% render_field field class="form-control is-valid" %}
                {% endif %}
                {% else %}
                {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-12 bg-danger my-2 text-white text-center"><h3>ENDEREÇO</h3></div>
            {% for field in endereco_form.visible_fields %}
            <div class="form-group col-6">
                {{ field.label_tag }}

                {% if endereco_form.is_bound %}
                {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
                {% endfor %}
                {% else %}
                {% render_field field class="form-control is-valid" %}
                {% endif %}
                {% else %}
                {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
            {% endfor %}
        </div>


        <input type="hidden"
               class="form-control" name="vendedor" value="{{ user.request.id }}">


        <button type="submit" class="btn btn-primary my-4">Cadastrar</button>
    </form>
  <a class="btn btn-primary mb-2" href="/dashboard" role="button">dashboard</a>
</div>

<script type="text/javascript">
		$("#id_cep").focusout(function(){
			//Início do Comando AJAX
			$.ajax({
				//O campo URL diz o caminho de onde virá os dados
				//É importante concatenar o valor digitado no CEP
				url: 'https://viacep.com.br/ws/'+$(this).val()+'/json/',
				//Aqui você deve preencher o tipo de dados que será lido,
				//no caso, estamos lendo JSON.
				dataType: 'json',
				//SUCESS é referente a função que será executada caso
				//ele consiga ler a fonte de dados com sucesso.
				//O parâmetro dentro da função se refere ao nome da variável
				//que você vai dar para ler esse objeto.
				success: function(resposta){
					//Agora basta definir os valores que você deseja preencher
					//automaticamente nos campos acima.
					$("#id_logradouro").val(resposta.logradouro);
					$("#id_complemento").val(resposta.complemento);
					$("#id_bairro").val(resposta.bairro);
					$("#id_cidade").val(resposta.localidade);
					$("#id_uf").val(resposta.uf);
					//Vamos incluir para que o Número seja focado automaticamente
					//melhorando a experiência do usuário
					$("#numero").focus();
				}
			});
		});


</script>


{% endblock %}

templates/cadastro_endereco.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--Importando Script Jquery-->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>


<!--        <div class="container">-->
<!--          &lt;!&ndash;Django Model Form&ndash;&gt;-->
<!--          <h2 class="my-4">ENDEREÇO</h2>-->
<!--          <form method="post" enctype="multipart/form-data">-->
<!--            {% csrf_token %}-->
<!--			  <input type="hidden" id="id_cliente" name="client" value="1">-->
<!--                {{endereco_form}}-->
<!--                <button class="btn btn-primary my-4" type="submit">Submit</button>-->
<!--          </form>-->
<!--          &lt;!&ndash;Django Model&ndash;&gt;-->


<!--        </div>-->


{% load widget_tweaks %}
<div class="container ">
    <div class=" p-3">
        <form method="post">
            {% csrf_token %}
            {% for hidden_field in endereco_form.hidden_fields %}
            {{ hidden_field }}
            {% endfor %}

            {% if endereco_form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in endereco_form.non_field_errors %}
                {{ error }}
                {% endfor %}
            </div>
            {% endif %}

            <div class="row border pb-2">
                <div class="col-12 bg-danger mb-2 text-white text-center"><h3>ENDEREÇO</h3></div>
                {% for field in endereco_form.visible_fields %}
                <div class="form-group col-6">
                    {{ field.label_tag }}

                    {% if endereco_form.is_bound %}
                    {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                    {% else %}
                    {% render_field field class="form-control is-valid" %}
                    {% endif %}
                    {% else %}
                    {% render_field field class="form-control" %}
                    {% endif %}

                    {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary my-2">Cadastrar</button>
        </form>
        <a class="btn btn-primary" href="/dashboard" role="button">dashboard</a>
    </div>
</div>

<script type="text/javascript">
		$("#id_cep").focusout(function(){
			//Início do Comando AJAX
			$.ajax({
				//O campo URL diz o caminho de onde virá os dados
				//É importante concatenar o valor digitado no CEP
				url: 'https://viacep.com.br/ws/'+$(this).val()+'/json/',
				//Aqui você deve preencher o tipo de dados que será lido,
				//no caso, estamos lendo JSON.
				dataType: 'json',
				//SUCESS é referente a função que será executada caso
				//ele consiga ler a fonte de dados com sucesso.
				//O parâmetro dentro da função se refere ao nome da variável
				//que você vai dar para ler esse objeto.
				success: function(resposta){
					//Agora basta definir os valores que você deseja preencher
					//automaticamente nos campos acima.
					$("#id_logradouro").val(resposta.logradouro);
					$("#id_complemento").val(resposta.complemento);
					$("#id_bairro").val(resposta.bairro);
					$("#id_cidade").val(resposta.localidade);
					$("#id_uf").val(resposta.uf);
					//Vamos incluir para que o Número seja focado automaticamente
					//melhorando a experiência do usuário
					$("#numero").focus();
				}
			});
		});

</script>


{% endblock %}

templates/cadastro_sem_endereco.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<!--Importando Script Jquery-->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>



<!--        <div class="container">-->
<!--          &lt;!&ndash;Django Model Form&ndash;&gt;-->
<!--          <h2 class="my-4">ENDEREÇO</h2>-->
<!--          <form method="post" enctype="multipart/form-data">-->
<!--            {% csrf_token %}-->
<!--			  <input type="hidden" id="id_cliente" name="client" value="1">-->
<!--                {{endereco_form}}-->
<!--                <button class="btn btn-primary my-4" type="submit">Submit</button>-->
<!--          </form>-->
<!--          &lt;!&ndash;Django Model&ndash;&gt;-->


<!--        </div>-->




{% load widget_tweaks %}
<div class="container">

  <form method="post" >
    {% csrf_token %}
    {% for hidden_field in cliente_form.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}


    {% if cliente_form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in cliente_form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}
    <div class="row">
      <div class="col-12 bg-danger my-2"> <h2>CLIENTE</h2></div>
      {% for field in cliente_form.visible_fields %}
        <div class="form-group col-6">
          {{ field.label_tag }}

          {% if cliente_form.is_bound %}
            {% if field.errors %}
              {% render_field field class="form-control is-invalid" %}
              {% for error in field.errors %}
                <div class="invalid-feedback">
                  {{ error }}
                </div>
              {% endfor %}
            {% else %}
              {% render_field field class="form-control is-valid" %}
            {% endif %}
          {% else %}
            {% render_field field class="form-control" %}
          {% endif %}

          {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}
        </div>
      {% endfor %}
    </div>

    <button type="submit" class="btn btn-primary mt-2">Submit</button>
  </form>
  <a class="btn btn-primary mt-3" href="/dashboard" role="button">dashboard</a>
</div>

	<script type="text/javascript">
		$("#id_cep").focusout(function(){
			//Início do Comando AJAX
			$.ajax({
				//O campo URL diz o caminho de onde virá os dados
				//É importante concatenar o valor digitado no CEP
				url: 'https://viacep.com.br/ws/'+$(this).val()+'/json/',
				//Aqui você deve preencher o tipo de dados que será lido,
				//no caso, estamos lendo JSON.
				dataType: 'json',
				//SUCESS é referente a função que será executada caso
				//ele consiga ler a fonte de dados com sucesso.
				//O parâmetro dentro da função se refere ao nome da variável
				//que você vai dar para ler esse objeto.
				success: function(resposta){
					//Agora basta definir os valores que você deseja preencher
					//automaticamente nos campos acima.
					$("#id_logradouro").val(resposta.logradouro);
					$("#id_complemento").val(resposta.complemento);
					$("#id_bairro").val(resposta.bairro);
					$("#id_cidade").val(resposta.localidade);
					$("#id_uf").val(resposta.uf);
					//Vamos incluir para que o Número seja focado automaticamente
					//melhorando a experiência do usuário
					$("#numero").focus();
				}
			});
		});
	</script>


{% endblock %}

templates/clientes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'partials/_clientes.html' %}
<div class="container text-center mb-5">
<img src="data:image/png;base64,{{ graphic|safe }}">
</div>
    <div class="container text-center mb-5">
<img src="data:image/png;base64,{{ graphic_valor|safe }}">
</div>

{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>

<div class="container border my-3">
    <div class="row p-3 bg-secondary text-white">
        <div class="h3">
            Total de vendas pagas no mes R${{venda}}
            <br>
            Valor a receber de comição R${{comicao_pendente}}
        </div>
    </div>
    <div class=" my-3">
    <a class="btn btn-primary" href="/cadastro_com_endereco" role="button">Cadastrar cliente completo</a>
    <a class="btn btn-primary" href="/cadastro_sem_endereco" role="button">Cadastrar cliente sem endereço</a>
    </div>
    {% include 'partials/_clientes.html' %}

    {% include 'partials/_tabela_pedidos.html' %}

    {% include 'partials/_tabela_produtos_mais_vendidos.html' %}


</div>









{% endblock %}

templates/tirar_pedido.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!--<div id="alert_placeholder"></div>-->
<!--{% if messages %}-->
<!--{% for message in messages %}-->
<!--<div class="alert alert-{{message.tags}}" role="alert">-->

<!--    {{ message }}-->

<!--</div>-->
<!--{% endfor %}-->
<!--{% endif %}-->

<div class="container mt-3">
    <div class="row">
        <div class="col-7">
            <h3 class="bg-danger p-3 text-center" >PRODUTOS</h3>
            <table class="table table-striped table-inverse table-responsive">

                <thead class="thead-default">
                <tr>
                    <th>Produto</th>
<!--                    <th>Valor</th>-->
                    <th>Qntd</th>
                    <th>Mg</th>
                    <th></th>
                </tr>
                </thead>
                <tbody class="table-group-divider">
                {% for produto in produtos0mg %}
                    {% include 'partials/_produto_tabela_mg.html' %}
                {% endfor %}
                </tbody>
            </table>
            </div>

            <div class='col-5'>
                <div id='pedido_carrinho'>

                    {% include 'partials/_items.html' %}

                </div>

            </div>



    </div>
</div>

{% endblock %}